name: EcommerceWeb2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup env
      run: |
          echo "\nENV_NAME=staging" >> .env
          pip install pipenv==2022.4.30

      - name: Create Deployment Dependencies File
        run: pipenv requirements > requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
