name: EcommerceWeb2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    
    services:
      image: sqlite3
      env:
      - SQLITE_ENGINE: django.db.backends.sqlite3
      -SQLITE_NAME: BASE_DIR / 'db.sqlite3'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip freeze > requirements.txt
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python3 -m venv venv
    - name: Run Tests   
      run: |
        venv\Scripts\activate.bat
        cd backend
        python manage.py test
